version: '3.1'
services:
  app:
    container_name: bootcamp
    image: bootcamp
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=password
      - POSTGRES_DB=test
